### ISSUE TITLE
swiper中页面多了会很卡

### ISSUE THREAD

**Issue by taiwandao** [pacochan/wxParser#1]
我现在遇到一个优化问题。我的页面原始数据是html，现在用的wxParse转wxml显示，但是我的页面是swiper，swiper下面有很多页面，每个页面都要使用wxParse转wxml显示，加载效率有点低，所以会很卡。不知道有没有更好的解决办法

**Comment by chenxingcai07** [comment]
@taiwandao 我觉得这种情况不适合从 wxParser 解析的层面去优化哦，应该是在使用的时候优化逻辑。比如你不要一次全部解析，可以在切换后再解析。

**Comment by taiwandao** [comment]
现在是切换后只解析当前一个页面的，但还是很卡，去掉解析的代码就不卡了

2017-03-07 11:00 GMT+08:00 paco <notifications@github.com>:

**Comment by chenxingcai07** [comment]
@taiwandao 感谢反馈。请问一下你要解析的 html 内容是多大的呢？比如说大概是多少数量级的 DOM 节点数？
