### ISSUE TITLE
你好，用这个库跑程序的时候，微信开发者工具提示有个模板找不到，我看了一下index.wxml里面没有wxParse12，因为自己对这个也不熟，请问有啥解决办法吗？谢谢。问题如下图：

### ISSUE THREAD

**Issue by xing00** [pacochan/wxParser#2]
<img width="775" alt="2017-06-12 2 56 04" src="https://user-images.githubusercontent.com/7943928/27022204-7ef62ddc-4f7f-11e7-9b67-93314b60487e.png">

**Comment by chenxingcai07** [comment]
@xing00 我已经更新代码修复这个 BUG 了，你更新代码即可。也可以看最新的 commit 来查看代码改动

**Comment by xing00** [comment]
我看了一下你的commit，添加了wxParser12上去了，但是同时12又指向了13，那13不是也没有吗？这样子有点写不完的感觉，还有14，15，16等等，我觉得是不是循环的时候出问题了？我更新了本地的代码，结果跟我想的一样，报wxParser13 not found。

**Comment by chenxingcai07** [comment]
@xing00 你的想法没错的，因为小程序模板不支持循环，只能用这种笨方法来处理。一般情况下没有这么深嵌套的，10 层都远远足够咯。你可以查一下相关的资料

**Comment by xing00** [comment]
原来是这样，谢谢啦，其实这个对页面没影响，我直接觉得有个not found不太好，然后就想问问看有没有解决办法，既然有10层就够了，那我就不管了，谢谢回复。
